use_frameworks!

platform :ios, '9.0'

target 'PodRepo2020_Example' do
  pod 'PodRepo2020', :path => '../'

  target 'PodRepo2020_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
