use_frameworks!

platform :ios, '9.0'

# pod 需要指定仓库 因为CocoaPods下没有的库需要指定 如下
#source 'https://github.com/CocoaPods/Specs.git'
#source 'https://github.com/zzjpeter/PodRepo2020.git'
#注意点：用本地库的时候 可能会报目录冲突错误，用一级目录就行，不用Classes、Assets的二级目录即可解决

target 'PodRepo2020_Example' do
  pod 'PodRepo2020','0.1.0', :inhibit_warnings => true# :path => '../'

  # pod lib lint 校验不通过的库 移s出 后需要手动添加
  #  测试
  pod 'LookinServer','1.0.0', :configurations => ['Debug'], :inhibit_warnings => true
  pod 'YYKit', '1.0.9', :inhibit_warnings => true
  
  target 'PodRepo2020_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end

